# fly.toml app configuration file generated for ramo-d on 2023-10-26T04:30:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ramo-d"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
